### ISSUE TITLE
Remove the tab index from headings

### ISSUE THREAD

**Issue by millipede-cpu** [fac-23/preA-week2-rayOli#16]
* You could remove `tab index` since the headings don't need to be focusable 🤓

**Comment by oliverjam** [comment]
(just copying what I wrote for another team in here for a little more context)

I would avoid making elements like `h2`s focusable. This isn't required for screen reader accessibility—they all have different ways to navigate through each element on the page/have everything read out to without needing to hit tab and focus each element. I would generally only make something focusable if there was an interaction required with that element.
